import type { Metadata } from 'next';
import Header from './components/Header';
import { GlobalStyles } from './globalStyles.js';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <GlobalStyles />
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
